apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wmmoia5mv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wmmoia5mv-go 
  name: wmmoia5mv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wmmoia5mv-go 
